### ISSUE TITLE
Unable to run python scripts for iOS application

### ISSUE THREAD

**Issue by sonalikal** [dweinstein/awesome-frida#3]
I am beginner in coding and it would be helpful if we could have examples to see how the already available scripts under Frida can be run for iOS application. For e.g for the script NSFileManager_Hooker how should the command to execute this process look like. I tried with something like python frida-scripts/NSFileManager_Hooker.py PROCESS_NAME. However i ran into an issue like frida.ProcessNotFoundError: unable to find process with name

**Comment by dweinstein** [comment]
Without more info I'm not sure I can be helpful. I would suggest you try consulting one of the videos/blog posts for info, check out the Frida telegram or IRC communities, or try asking your question again over [here](https://github.com/frida/frida/issues).
